#!/usr/bin/env bash
# Install nginx web server using bash
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx start
