#!/usr/bin/env bash
#HTTP response with a custom header

sudo apt update
sudo apt install -y nginx
sudo sed -i "s/listen \[::\]:80 default_server;/&\n\alx-header X-Served-By $HOSTNAME;/" /etc/nginx/sites-enabled/default
sudo service nginx restart
