#!/usr/bin/env bash
#HTTP response with a custom header

sudo apt update
sudo apt install -y nginx
sudo sed -i '/listen 80;/a \alx_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx restart
