#!/usr/bin/env bash
#script that displays Best School 10 times and Hi at 9th
i=1
j=10
while [ $i -le $j ];
do
  case $i in
    4 )
      echo "4"
      echo "bad luck from China";;
    9 )
      echo "9"
      echo "bad luck from Japan";;
    17 )
      echo "17"
      echo "bad luck from Italy";;
    *)
      echo "$i"
  esac
  ((i++))
done
