#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
j=1
while [ $i -le 12 ];
do
  echo "Hour: $i"
  while [ $j -le 59 ];
  do
    echo "$j"
    ((j++))
  done
  j=1
  ((i++))
done
